// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// predict_map_cpp
Rcpp::List predict_map_cpp(arma::mat data, Rcpp::List mcmc_sample, arma::mat dist_11, arma::mat dist_12, arma::mat dist_22, Rcpp::List params, int inner_reps, Rcpp::List args_progress, Rcpp::List args_functions, Rcpp::List args_misc);
RcppExport SEXP _genescaper_predict_map_cpp(SEXP dataSEXP, SEXP mcmc_sampleSEXP, SEXP dist_11SEXP, SEXP dist_12SEXP, SEXP dist_22SEXP, SEXP paramsSEXP, SEXP inner_repsSEXP, SEXP args_progressSEXP, SEXP args_functionsSEXP, SEXP args_miscSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type mcmc_sample(mcmc_sampleSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dist_11(dist_11SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dist_12(dist_12SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dist_22(dist_22SEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< int >::type inner_reps(inner_repsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args_progress(args_progressSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args_functions(args_functionsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args_misc(args_miscSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_map_cpp(data, mcmc_sample, dist_11, dist_12, dist_22, params, inner_reps, args_progress, args_functions, args_misc));
    return rcpp_result_gen;
END_RCPP
}
// get_mean_pairwise_Gst_cpp
arma::mat get_mean_pairwise_Gst_cpp(arma::field<arma::mat> freq_list);
RcppExport SEXP _genescaper_get_mean_pairwise_Gst_cpp(SEXP freq_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type freq_list(freq_listSEXP);
    rcpp_result_gen = Rcpp::wrap(get_mean_pairwise_Gst_cpp(freq_list));
    return rcpp_result_gen;
END_RCPP
}
// predict_pairwise_Gst_cpp
Rcpp::List predict_pairwise_Gst_cpp(arma::field<arma::mat> data_list, Rcpp::List mcmc_sample, arma::mat dist_11, Rcpp::List params, int inner_reps, Rcpp::List args_progress, Rcpp::List args_functions, Rcpp::List args_misc);
RcppExport SEXP _genescaper_predict_pairwise_Gst_cpp(SEXP data_listSEXP, SEXP mcmc_sampleSEXP, SEXP dist_11SEXP, SEXP paramsSEXP, SEXP inner_repsSEXP, SEXP args_progressSEXP, SEXP args_functionsSEXP, SEXP args_miscSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type mcmc_sample(mcmc_sampleSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dist_11(dist_11SEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< int >::type inner_reps(inner_repsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args_progress(args_progressSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args_functions(args_functionsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args_misc(args_miscSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_pairwise_Gst_cpp(data_list, mcmc_sample, dist_11, params, inner_reps, args_progress, args_functions, args_misc));
    return rcpp_result_gen;
END_RCPP
}
// GeoMAPI_assign_edges_cpp
Rcpp::List GeoMAPI_assign_edges_cpp(Rcpp::List args, Rcpp::List args_functions, Rcpp::List args_progress, arma::mat dist_11);
RcppExport SEXP _genescaper_GeoMAPI_assign_edges_cpp(SEXP argsSEXP, SEXP args_functionsSEXP, SEXP args_progressSEXP, SEXP dist_11SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args_functions(args_functionsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args_progress(args_progressSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dist_11(dist_11SEXP);
    rcpp_result_gen = Rcpp::wrap(GeoMAPI_assign_edges_cpp(args, args_functions, args_progress, dist_11));
    return rcpp_result_gen;
END_RCPP
}
// sim_wrightfisher_cpp
Rcpp::List sim_wrightfisher_cpp(Rcpp::List args, Rcpp::List args_functions, Rcpp::List args_progress);
RcppExport SEXP _genescaper_sim_wrightfisher_cpp(SEXP argsSEXP, SEXP args_functionsSEXP, SEXP args_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args_functions(args_functionsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args_progress(args_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_wrightfisher_cpp(args, args_functions, args_progress));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_genescaper_predict_map_cpp", (DL_FUNC) &_genescaper_predict_map_cpp, 10},
    {"_genescaper_get_mean_pairwise_Gst_cpp", (DL_FUNC) &_genescaper_get_mean_pairwise_Gst_cpp, 1},
    {"_genescaper_predict_pairwise_Gst_cpp", (DL_FUNC) &_genescaper_predict_pairwise_Gst_cpp, 8},
    {"_genescaper_GeoMAPI_assign_edges_cpp", (DL_FUNC) &_genescaper_GeoMAPI_assign_edges_cpp, 4},
    {"_genescaper_sim_wrightfisher_cpp", (DL_FUNC) &_genescaper_sim_wrightfisher_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_genescaper(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
