// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// predict_map_cpp
Rcpp::List predict_map_cpp(Rcpp::List data_list, Rcpp::List mcmc_sample, Rcpp::NumericMatrix dist_11, Rcpp::NumericMatrix dist_12, Rcpp::NumericMatrix dist_22, Rcpp::List params, int inner_reps, Rcpp::List args_progress, Rcpp::List args_functions, Rcpp::List args_misc);
RcppExport SEXP _genescaper_predict_map_cpp(SEXP data_listSEXP, SEXP mcmc_sampleSEXP, SEXP dist_11SEXP, SEXP dist_12SEXP, SEXP dist_22SEXP, SEXP paramsSEXP, SEXP inner_repsSEXP, SEXP args_progressSEXP, SEXP args_functionsSEXP, SEXP args_miscSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type mcmc_sample(mcmc_sampleSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type dist_11(dist_11SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type dist_12(dist_12SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type dist_22(dist_22SEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< int >::type inner_reps(inner_repsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args_progress(args_progressSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args_functions(args_functionsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args_misc(args_miscSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_map_cpp(data_list, mcmc_sample, dist_11, dist_12, dist_22, params, inner_reps, args_progress, args_functions, args_misc));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_genescaper_predict_map_cpp", (DL_FUNC) &_genescaper_predict_map_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_genescaper(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
