# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predict_map_cpp <- function(data_list, mcmc_sample, dist_11, dist_12, dist_22, params, inner_reps, args_progress, args_functions, args_misc) {
    .Call(`_genescaper_predict_map_cpp`, data_list, mcmc_sample, dist_11, dist_12, dist_22, params, inner_reps, args_progress, args_functions, args_misc)
}

