# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predict_map_cpp <- function(data, mcmc_sample, dist_11, dist_12, dist_22, params, inner_reps, args_progress, args_functions, args_misc) {
    .Call(`_genescaper_predict_map_cpp`, data, mcmc_sample, dist_11, dist_12, dist_22, params, inner_reps, args_progress, args_functions, args_misc)
}

null_map_cpp <- function(data, mcmc_sample, dist_11, dist_22, params, inner_reps, args_progress, args_functions, args_misc) {
    .Call(`_genescaper_null_map_cpp`, data, mcmc_sample, dist_11, dist_22, params, inner_reps, args_progress, args_functions, args_misc)
}

null_site_cpp <- function(data, mcmc_sample, dist_11, params, inner_reps, args_progress, args_functions, args_misc) {
    .Call(`_genescaper_null_site_cpp`, data, mcmc_sample, dist_11, params, inner_reps, args_progress, args_functions, args_misc)
}

GeoMAPI_assign_edges_cpp <- function(args, args_functions, args_progress, dist_11) {
    .Call(`_genescaper_GeoMAPI_assign_edges_cpp`, args, args_functions, args_progress, dist_11)
}

sim_wrightfisher_cpp <- function(args, args_functions, args_progress) {
    .Call(`_genescaper_sim_wrightfisher_cpp`, args, args_functions, args_progress)
}

